services:
  - type: web
    name: v380-cctv-backend
    runtime: docker
    rootDir: .
    plan: starter
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: FFMPEG_PATH
        value: ffmpeg
      - key: ENABLE_LAN_DISCOVERY
        value: "false"
      - key: TAILSCALE_AUTHKEY
        sync: false
      - key: TAILSCALE_HOSTNAME
        value: v380-backend
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URLS
        sync: false
      - key: JWT_EXPIRE
        value: 7d
      - key: RECORDINGS_PATH
        value: /var/data/recordings
      - key: MAX_STORAGE_GB
        value: "10"
      - key: AUTO_DELETE_ON_FULL
        value: "true"
    disk:
      name: recordings
      mountPath: /var/data
      sizeGB: 10
